### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by raphaelli** [timvisee/docker-mssql#1]
i use "docker-compose up" to start this ,but it's error wiht "mssql_mssql_1 exited whit code 1"

do you know how to fix this ?

**Comment by raphaelli** [comment]
sorry about that 

i look you "start" ,add "-d" can fix this !

**Comment by timvisee** [comment]
Weird that it caused errors though. But, using `./start` (or `docker-compose start -d` fixed it)? Awesome!

**Comment by raphaelli** [comment]
In fact, it still error whit this !
using "-d" will make it start ,but after a few second ,it will be exited!
I used an another docker-compose file , maybe you should have a look !

https://github.com/uniteeio/mssql_server_docker-compose

**Comment by timvisee** [comment]
Weird. It is working on my machine, just tried it. Maybe Docker is having trouble mounting to your machine, that's the only real difference I'm seeing.

In that case using a volume would be possible, by configuring a volume and chaining the current volume being used like this:

```yaml
mssql:
  # ...
  volumes:
    - 'mssql_volume:/mnt/drive'

volumes:
  mssql_volume:
```

**Comment by raphaelli** [comment]
I‘m sorry , that's all my fault ！
i change the password ，but it don't accepted by mssql , so …… 
Sorry to disturb you again ！

and i still have some trouble with this ， maybe you can help ？

After i connect this mssql on docker by navicat， I can’t find any database in it , and i can't creat database neither.

navicat notice :
42000 - [SQL Server] A file activation error occurred. The physical file name ‘\test.ndf’ maybe incorrect. Diagnose and correct additional errors , and retry the operation.
42000 - [SQL Server] CREATE DATABASE faild. Some file names listed could not be created. Check related errors.

Have you meet this encountered this situation before ? Or you have any idea to solve this ？

**Comment by timvisee** [comment]
Weird, again. By default, no database is created, and one must be created using the super administrator (`sa`) user. And no, I did not come across this issue.

Maybe removing the mount contents, and starting a fresh instance might help? I don't know.

Note though, that this repository only provides a very simple `docker-compose` configuration to easily start the container. The container image itself is provided by Microsoft. You might have better luck on their image issue board [here](https://github.com/Microsoft/mssql-docker/issues).

Good luck though!
