### ISSUE TITLE
Query about volume

### ISSUE THREAD

**Issue by rasodu** [timvisee/docker-mssql#2]
What purpose of volume './drive:/mnt/drive'? I have been trying to find documentation on it with no luck.

**Comment by timvisee** [comment]
Microsoft their container uses the `/mnt/drive` directory to store all database data. Did a quick search on their Docker Hub page but couldn't find anything on it either. Anyhow, that's what the directory is for.

The purpose of `./drive:/mnt/drive` is to create a `drive` directory in the working directory you're using the compose configuration from, which then stores the database data.

You can change the `./drive` part to whatever directory you may like. If you remove the mount all together, data won't be preserved if the container is restarted.
